apiVersion: v1
kind: Pod
metadata:
  labels:
    run: falco-nginx
  name: falco-nginx
spec:
  containers:
  - command: ['/bin/sh']
    args: ['-c', 'apk add vim; sleep inf']
    image: nginx:alpine
    name: falco-nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

