
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: falco-httpd
  name: falco-httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: falco-httpd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: falco-httpd
    spec:
      containers:
      - image: httpd:alpine
        name: falco-httpd
        command: ['/bin/sh']
        args: ['-c', 'while true; do echo hello > /etc/passwd; sleep 10; done']
        resources: {}

