apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: immutable-real-only-fs
  name: immutable-real-only-fs
spec:
  containers:
  - image: httpd
    name: immutable-real-only-fs
    resources: {}
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
    - mountPath: /usr/local/apache2/logs
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volume:
status: {}
